config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "welcome#index"
  get "/information", to: 'welcome#information'
  resources :lessons, only: [:create, :new, :show]
  resources :top, only: [:create, :index, :new] do
    collection do
      get :search, :information
    end
  end
  resources :lessons_users, only: [:destroy] do
    collection do
      delete :all_destroy
    end
  end
  resources :users, only: [:edit, :update]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
  has_many :lessons
  has_many :teachers

  belongs_to :faculty
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :departments
end

app/models/gread.rb
class Gread < ApplicationRecord
   has_many :lessons
   has_many :users
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :department
  belongs_to :gread
  belongs_to :year

  has_many :users, through: :lesson_users
  has_many :lesson_users
  has_many :books
end

app/models/lesson_teacher.rb
class LessonTeacher < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :teacher
end

app/models/lesson_user.rb
class LessonUser < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :user

  scope :lesson_user, ->(id){LessonUser.find(id)}
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :lessons

  belongs_to :department
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :department
  belongs_to :gread

  has_many :lesson_users
  has_many :lessons, through: :lesson_users
  has_many :user_books
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @q = Lesson.includes(:teacher).ransack(params[:q])
    # @lessons = @q.result(distinct: true)

    # if user_signed_in?
    #   @lessons = current_user.lessons
    # else
    #   redirect_to new_user_session_path
    # end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lessons =
      Lesson.includes(:teacher).where(
        "department_id = ? AND
        wday = ? AND
        period = ? AND
        gread_id <= ? AND
        term_id in (?) AND
        gread_id <= ? AND
        department_id = ?",
        current_user.department_id,
        params[:wday],
        params[:period],
        params[:gread_id],
        params[:term_id],
        params[:gread_id],
        params[:department_id]
      )
    @user_status = LessonUser.new
  end

  def create
    lessonUser_create['lesson_ids'].split(' ').each do |t|
      lesson = LessonUser.new
      lesson.lesson_id = t
      lesson.user_id = current_user.id
      lesson.save
    end

    redirect_to "/"
  end

  def search
    @q = Lesson.includes(:teacher).search(search_params)
    @lessons = @q.result(distinct: true)
    @user_status = LessonUser.new
  end

  private
  def search_params
    params.require(:q).permit(:name_cont)
  end

  def lessonUser_create
    params.require(:lesson_user).permit(:lesson_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/layouts/_footer.html.haml
%footer#footer
  Copyright(c) 20XX Sample Inc. All Rights Reserved. Design by
  %a{:href => "http://f-tpl.com", :target => "_blank"} http://f-tpl.com
  / ←クレジット表記を外す場合はシリアルキーが必要です http://f-tpl.com/credit/

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-wight
  .navbar-brand
    = link_to '/' do
      %img.logo-mark{:alt => "ふぁしり", :src => "/assets/facili_logo_mark.png"}
  %button.navbar-toggler{"aria-controls" => "Navber", "aria-expanded" => "false", "aria-label" => "ナビゲーションの切替", "data-target" => "#Navber", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #Navber.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        - if user_signed_in?
          %li.nav-link
            = link_to"プロフィール編集", "/users/#{current_user.id}/edit"
          %li.nav-link
            = link_to"ログアウト",destroy_user_session_path, method: :delete
          %li.nav-link
            = link_to'このサイトの使い方','/top/information'
          - if current_user.permission == "administrator"
            %li.nav-link
              = link_to"授業登録","/lessons/new", method: :get
        - else
          %li.nav-link
            = link_to"新規登録",new_user_registration_path
          %li.nav-link
            = link_to"ログイン",new_user_session_path
          %li.nav-link
            = link_to'このサイトの使い方','/information'
    -#     %a.nav-link{:href => "#"}
    -#       ホーム
    -#       %span.sr-only (現位置)
    -#   %li.nav-item
    -#     %a.nav-link{:href => "#"} リンク
    -#   %li.nav-item.dropdown
    -#     %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    -#       ドロップダウン
    -#     .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
    -#       %a.dropdown-item{:href => "#"} メニュー1
    -#       %a.dropdown-item{:href => "#"} メニュー2
    -#       .dropdown-divider
    -#       %a.dropdown-item{:href => "#"} その他
    -#   %li.nav-item
    -#     %a.nav-link.disabled{:href => "#"} 無効
    -# %form.form-inline.my-2.my-lg-0
    -#   %input.form-control.mr-sm-2{"aria-label" => "検索...", :placeholder => "検索...", :type => "search"}/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} 検索
  / /.navbar-collapse


  -# %header
  -#   = link_to '/' do
  -#     %img.logo-marks{:alt => "ふぁしり", :src => "/assets/facili_logo_mark.png", class: 'mt-2'}
  -#   .head-btns.pull-right.mt-3
  -#     - if user_signed_in?
  -#       = link_to"プロフィール編集", "/users/#{current_user.id}/edit", class: "btn btn-success py-4"
  -#       = link_to"ログアウト",destroy_user_session_path, method: :delete, class: "btn btn-warning py-4"
  -#       = link_to'このサイトの使い方','/top/information', class: "btn btn-primary mr-2 py-4"
  -#       - if current_user.permission == "administrator"
  -#         = link_to"授業登録","/lessons/new", method: :get, class: "btn btn-light"
  -#     - else
  -#       = link_to"新規登録",new_user_registration_path, class: "btn btn-success py-4"
  -#       = link_to"ログイン",new_user_session_path, class: "btn btn-info py-4"
  -#       = link_to'このサイトの使い方','/top/information', class: "btn btn-primary py-4"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width; initial-scale=1.0;"}
    %link{:href => "/template_assets/css/style.css", :rel => "stylesheet"}/
    %title FaciliBooks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"


    %script{:src => "/template_assets/js/script.js"}